export const THEME_COLORS = [
  { name: 'Classic Blue', value: '#1F68D3' },
  { name: 'Sky Blue', value: '#3FC8DD' },
  { name: 'Magenta', value: '#E828A9' },
  { name: 'Violet', value: '#5161FE' },
  { name: 'Ocean Blue', value: '#3596FA' },
  { name: 'Emerald', value: '#3CB371' },
  { name: 'Pink', value: '#FB7299' },
  { name: 'Purple', value: '#9A6EE3' },
  { name: 'Coral', value: '#FE5157' },
  { name: 'Royal Blue', value: '#3875C6' },
  { name: 'Azure', value: '#76B5FF' },
  { name: 'Dodger Blue', value: '#0086FF' },
  { name: 'Golden', value: '#FFB50A' },
  { name: 'Rose', value: '#F2176D' },
  { name: 'Salmon', value: '#FF8983' },
  { name: 'Deep Blue', value: '#0057dc' },
  { name: 'Red', value: '#FF0000' },
  { name: 'Lime', value: '#93D200' },
];
